#\u6784\u9020\u4E00\u4E2A\u5BF9\u8C61 \u5305\u542B\u57FA\u672C\u6570\u636E\u7C7B\u578B\u4EE5\u53CAString \u4EE5\u53CA\u5BF9\u8C61\u6CDB\u578B\u7684list\u5B57\u6BB5
leilei:
  #\u540D\u5B57
  name: leilei
  #\u5E74\u9F84
  age: 22
  #\u6027\u522B
  sex: true
  #\u5973\u670B\u53CB\u4EEC
  girlfriends:
    - name: luci
      age: 21
      cup: C
    - name: meimei
      age: 22
      cup: D
    - name: keke
      age: 21
      cup: A
    - name: panghu
      age: 22
      cup: D

# \u8BFB\u53D6\u9879\u76EEPOM.xml \u6587\u4EF6\u4FE1\u606F
myapplication:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
  name: @project.name@
  description: @project.description@