spring:
  activemq:
    #ActiveMQ
    broker-url: tcp://47.97.118.22:61616
    user: admin
    password: 123456
    #默认包名安全 （支持序列化反序列化）
    packages:
      trust-all: true
  #支持topic模式
  jms:
    pub-sub-domain: true