jwt:
  # \u5BC6\u94A5
  secret: 'lei#ae86..'
  #token\u8FC7\u671F\u65F6\u95F4  \u5355\u4F4D\u5C0F\u65F6
  expireTime: 12
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

