spring:
  rabbitmq:
    #我这里仅写了ip 其余端口账号密码由于是演示 采用默认即可，不必要写
    host: xxx
    # 开启消息确认机制 confirm 异步
    publisher-confirm-type: correlated
    listener:
      direct:
        # 消息开启手动确认
        acknowledge-mode: manual
    publisher-returns: true
  main:
    allow-bean-definition-overriding: true